### ISSUE TITLE
Y U No has wiki?!

### ISSUE THREAD

**Issue by Abizern** [danielctull/DCTCoreDataStack#2]

**Comment by danielctull** [comment]
There's full documentation at http://danieltull.co.uk/DCTCoreDataStack/documentation/, does this help? 

Regardless, I'm going to continue with sitting in the middle of Munich, eating pretzels and watching beer drinking locals. :-)

**Comment by Abizern** [comment]
Sorry - I forgot you were away.

**Comment by Abizern** [comment]
The docs are fine and answered the question that I wanted to ask you on Chat. I wanted to add a link to Scotty's tutorial in the wiki.

**Comment by danielctull** [comment]
Umm best place might be to add it to the readme? :-)

Also, GitHub seem not to allow emoji in comments.

**Comment by Abizern** [comment]
Closing this as it's redundant.
