### ISSUE TITLE
Add support to load merged bundles from all bundles, not just the main bundle.

### ISSUE THREAD

**Issue by Abizern** [danielctull/DCTCoreDataStack#8]
Currently, when a nil modelURL is passed in the initialiser, then only the models from the mainBundle are loaded https://github.com/danielctull/DCTCoreDataStack/blob/master/DCTCoreDataStack/DCTCoreDataStack.m#L177

However, sometimes it is useful to be able to load the merged models from all bundles, which this method does not currently support.

Because it breaks backwards compatibility, this can't be changed to load from all bundles instead of just the main bundle.

Options are:
- Create a new initialiser that sets a flag that the _loadManagedObjectModel can check to load from all bundles or just the main bundle
- Use a block based initialiser that allows control over what models are loaded
- A delegate method which allows the model urls or the bundles to be searched to be passed in.

**Comment by mikeabdullah** [comment]
Why? This is generally a very bad idea.

When `NSPersistentDocument` shipped in 10.4, by default it produced a model merged from all bundles. This was nice and convenient, but there is a major problem: all bundles includes things like system frameworks. The result was a model that depended on other models in system frameworks (non-public API) remaining the same. Of course, in 10.5 they didn't, and many apps ran into big trouble that way.

**Comment by Abizern** [comment]
Mike - this is for a library which uses a managed object model loaded from a separate bundle. The consumers of the library may wish to add their own models alongside the one I'm providing.

**Comment by danielctull** [comment]
While I agree with Mike, it is the case that there is currently no way to have multiple models merged together.

Currently you have to have different stacks for separate models.

**Comment by Abizern** [comment]
Despite our long conversation about this, I've been looking at this some more and, in reality, I should really just pass in the models that I want rather than just shotgunning them all in. While my hotfix "works" I'm still not sure that I shouldn't just pass in the model's url, or an array of models to merge.

**Comment by Abizern** [comment]
That was a complete waste of time :( I just wrote a method that looks for the particular modelURL that I want to load and used that. 

However, the idea you originally had about passing in an array of model URLs is still a good one, and maybe leave this open so you're reminded about it.

**Comment by danielctull** [comment]
I also wonder whether separate stacks/stores for separate models is better to handle model migrations…

**Comment by Abizern** [comment]
How would you feel about changing this line:

```
_managedObjectModel = [NSManagedObjectModel mergedModelFromBundles:[NSArray arrayWithObject:[NSBundle mainBundle]]];
```

to this?

```
_managedObjectModel = [NSManagedObjectModel mergedModelFromBundles:[NSArray arrayWithObject:[NSBundle bundleForClass:[self class]]]];
```

Which works when loading from a library and doesn't break backwards compatibility.

Unless I'm being really stupid?

**Comment by danielctull** [comment]
Does it work?

That looks like it'll load all the models in the DCTCoreDataStack static library bundle? Which is none… unless I'm missing something?

**Comment by Abizern** [comment]
It works.. Even when it's loaded from a static library.. Which is my use case.  And it works when loaded by a test bundle that has the model in its resources.

**Comment by danielctull** [comment]
What I don't understand is that the model can not be in the same bundle as the DCTCoreDataStack static library or in any static library!

**Comment by danielctull** [comment]
Okay, so after reading the docs, `-[NSBundle bundleForClass:]` just returns the main bundle for classes defined in static libraries, so I'm confused as the lines above would be equivalent?

**Comment by Abizern** [comment]
For the _loading_ library.  The app that links against the library has the model in its bundle. 

## 

Abizer
